import Head from "next/head";
import '@aws-amplify/ui-react/styles.css';
import {
  defaultDarkModeOverride,
  ThemeProvider
} from '@aws-amplify/ui-react';
import NavBar from "../components/navbar";
import '@fontsource/inter/variable.css';
import { PostsCreateForm } from "../src/ui-components"

export default function CreateForm() {
    
    const theme = {
        name: 'my-theme',
        overrides: [defaultDarkModeOverride],
    };

    return (
        <div className="bg-cover bg-accent-dark">
            <Head>
                <title>albac: home</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <NavBar title="Portfolio" />
                <div className="mt-40 px-60">
        <ThemeProvider theme={theme} colorMode="system">
                  <PostsCreateForm mode='Dark' />
        </ThemeProvider>
                </div>
            </main>
        </div>
    );
}
