import Head from "next/head";
import Link from "next/link";
import { format, parseISO } from "date-fns";
import { getAllPosts } from "../lib/data";
import NavBar from "../components/navbar";

export default function Projects({ posts }) {
    return (
        <div className="bg-accent-dark">
            <Head>
                <title>albac: projects</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <NavBar title="Projects" />
                <div className="mt-24 h-screen bg-slate-100 dark:bg-slate-900 bg-daytime dark:bg-hero overflow-auto scroll-smooth">
                <div className="flex justify-center flex-grow">
                    <div className="flex px-8">
                        <div className="space-y-10 mt-10 ">
                            {posts.map((item) => (
                                <BlogListItem key={item.slug} {...item} />
                            ))}
                        </div>
                    </div>
                </div>
                </div>
            </main>
        </div>
    );
}

export async function getStaticProps() {
    const allPosts = getAllPosts();

    return {
        props: {
            posts: allPosts
                .slice(0)
                .reverse()
                .map(({ data, slug }) => ({
                    ...data,
                    date: data.date.toISOString(),
                    content: data.summary,
                    slug,
                })),
        },
    };
}

function BlogListItem({ slug, title, date, content }) {
    return (
        <div className="border font-light text-lg space-y-2 hover:border-slate-400 dark:bg-slate-800 dark:border-white/5 border-black-400 rounded p-4">
            <div>
                <Link href={`/blog/${slug}`}>
                    <button className="text-blue-600 hover:text-blue-500 dark:text-sky-400 font-semibold antialiased">
                        {title}
                    </button>
                </Link>
            </div>
            <div className="text-xs text-gray-600 dark:text-gray-200">
                {format(parseISO(date), "MMMM do, uuu")}
            </div>
            <div className="italic">{content}</div>
        </div>
    );
}
