import Head from "next/head";
import '@aws-amplify/ui-react/styles.css';
import {
  defaultDarkModeOverride,
  ThemeProvider
} from '@aws-amplify/ui-react';
import NavBar from "../../components/navbar";
import '@fontsource/inter/variable.css';
import { useRouter } from 'next/router';
import { PostsUpdateForm } from "../../src/ui-components";
import { useState } from 'react';

export default function EditBlogPage() {

    const [showSuccess, setShowSuccess] = useState(false)
    const [errorMessage, setErrorMessage] = useState(false)

    const router = useRouter()
    const { id } = router.query
    
    const theme = {
        name: 'my-theme',
        overrides: [defaultDarkModeOverride],
    };

    return (
        <div className="bg-cover bg-accent-dark">
            <Head>
                <title>albac: home</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <NavBar title="Portfolio" />
                <div className="mt-40 px-60">
        <>
        {showSuccess &&
            <p>Record updated!</p>
        }
        </>
        <>
        {errorMessage &&
                <p>Error: {errorMessage}</p>
        }
        </>
        <ThemeProvider theme={theme} colorMode="system">
                  <PostsUpdateForm mode='Dark' id={id} onSuccess={() => { setShowSuccess(true) }} onError={(error) => { setErrorMessage(error)}}/>
        </ThemeProvider>
                </div>
            </main>
        </div>
    );
}
